### ISSUE TITLE
app 使用方面的问题

### ISSUE THREAD

**Issue by Xiao-La** [fR0Z863xF/FuuleaEnvEmu#1]
这个 app 中的 sn 和账户怎么填？我并不了解领创的管控相关的信息。这个软件使用不需要 root 权限或其他权限吗？

**Comment by fR0Z863xF** [comment]
sn是设备序列号，填这个就行。账号不用填可以。  
这个app我没申请任何权限，因为不需要（可以看代码里面的androidmanifest文件）

**Comment by Xiao-La** [comment]
在自己的 Android 设备上成功使用。感谢。
