### ISSUE TITLE
如果已经是Iauncher3了有解决方案吗

### ISSUE THREAD

**Issue by Breeze1733** [fR0Z863xF/FuuleaEnvEmu#2]
感谢

**Comment by Breeze1733** [comment]
我还没安装，不介意的话也说说有什么恶劣后果吧

**Comment by fR0Z863xF** [comment]
原生安卓默认桌面包名就是com.android.launcher3，安卓允许用户覆盖安装包名与com.android.launcher3相同的软件（部分第三方桌面包名就是这个）。你可以想想会变成什么样。

**Comment by Breeze1733** [comment]
那我找第三方的桌面安装就可以用这个APP了么

**Comment by Breeze1733** [comment]
因为我给机器刷进去的系统包是原生系统，桌面包肯定是launcher的

**Comment by Breeze1733** [comment]
能推荐个第三方桌面包给我使用吗，一些简单的adb调试我还是可以操作的

**Comment by fR0Z863xF** [comment]
我只用过niagara launcher，你可以搜一下一下有没有其他系统移植的启动器

**Comment by Breeze1733** [comment]
换一个桌面启动器应该就没有这方面的问题了对吧

**Comment by fR0Z863xF** [comment]
理论上可以。不过既然你可以刷机，不如做个模块。

**Comment by Breeze1733** [comment]
什么模块，具体说说

**Comment by fR0Z863xF** [comment]
自己做一个

**Comment by Breeze1733** [comment]
好吧谢谢啦
