### ISSUE TITLE
已安装辅立码课2.3 配置已保存 点击启动app时显示启动失败是怎么回事

### ISSUE THREAD

**Issue by jindingming** [fR0Z863xF/FuuleaEnvEmu#3]

**Comment by fR0Z863xF** [comment]
手动启动就行

**Comment by jindingming** [comment]
> 手动启动就行

![Screenshot_2024-04-04-10-37-34-586_com.fuulea.venus.g.png](https://github.com/fR0Z863xF/FuuleaEnvEmu/assets/165936631/43dfd218-38c1-4c80-8b10-a7398b64ecb5)

无法登录

**Comment by fR0Z863xF** [comment]
先启动本app，再开辅立码课。本app内启动失败是高版本安卓限制的问题

**Comment by jindingming** [comment]
> 先启动本app，再开辅立码课。本app内启动失败是高版本安卓限制的问题

仍然无法登录 辅立码课显示不允许在此设备登陆

**Comment by fR0Z863xF** [comment]
sn要填平板的，不是你手机的。a
开辅立码课前确保app在后台运行。更新配置完要杀掉辅立码课再开
